'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  ArrowRight, BarChart3, BellRing, Check, ChevronDown, ChevronRight, CircleDollarSign,
  Globe2, Laptop, Mail, Menu, MapPin, Monitor, PackageSearch, Radar, RefreshCw,
  ShieldCheck, Smartphone, Sparkles, Target, TrendingUp, Users, X, Zap,
} from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const trendData = [
  { name: '1月', value: 18 }, { name: '2月', value: 25 }, { name: '3月', value: 23 },
  { name: '4月', value: 36 }, { name: '5月', value: 42 }, { name: '6月', value: 51 },
]
const marketData = [
  { name: '北美', value: 82 }, { name: '欧洲', value: 64 }, { name: '东南亚', value: 57 }, { name: '中东', value: 41 },
]
const tabs = ['市场机会', '利润测算', '税务', '物流时效', '风险提示']
const faqs = [
  ['PickGlobal 适合哪些企业？', '适合跨境电商卖家、外贸工厂、品牌出海团队和外贸服务商，尤其适合需要持续寻找市场与客户的团队。'],
  ['可以分析自有商品吗？', '可以。支持手动录入、CSV 导入以及国内商品数据接口，让自有商品快速进入分析工作台。'],
  ['首期支持哪些市场？', '首期支持中国与美国市场，后续将持续扩展更多国家和地区。'],
  ['如何获取潜在客户？', '系统会根据地区、行业与产品相关性筛选潜在客户，帮助团队建立更精准的客户池。'],
  ['AI 会自动发送邮件吗？', 'AI 负责生成个性化内容与触达建议，发送前由团队确认，确保每一次沟通都符合品牌语气。'],
  ['是否支持多端使用？', '支持 Web、微信小程序、Android、iOS、macOS 和 Windows，多端同步同一个工作台。'],
]

function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <div className="mx-auto flex max-w-2xl flex-col items-center gap-4 text-center"><span className="eyebrow">{eyebrow}</span><h2 className="text-balance text-3xl font-semibold tracking-tight text-foreground md:text-5xl">{title}</h2>{copy && <p className="text-pretty text-base leading-7 text-muted-foreground md:text-lg">{copy}</p>}</div>
}

function DashboardPreview() {
  return <div className="dashboard-shell animate-float" aria-label="PickGlobal 商品分析工作台演示">
    <div className="flex items-center justify-between border-b border-border/70 px-4 py-3 md:px-5"><div className="flex items-center gap-2"><div className="flex size-7 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Globe2 className="size-4" /></div><span className="text-xs font-semibold">商品分析工作台</span></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-medium text-emerald-700">演示数据</span></div>
    <div className="grid gap-3 p-4 md:grid-cols-[1.05fr_.95fr] md:p-5">
      <div className="flex flex-col gap-3"><div className="rounded-xl border border-border bg-muted/35 p-3"><div className="flex items-center justify-between"><div><p className="text-[10px] text-muted-foreground">当前分析商品</p><p className="mt-1 text-sm font-semibold">智能温控水杯 · 500ml</p></div><PackageSearch className="size-5 text-primary" /></div><div className="mt-4 flex items-center gap-2"><span className="rounded-md bg-primary/10 px-2 py-1 text-[10px] font-medium text-primary">美国市场</span><span className="rounded-md bg-emerald-50 px-2 py-1 text-[10px] font-medium text-emerald-700">机会较高</span></div></div><div className="grid grid-cols-2 gap-3"><Metric label="商品机会分" value="86" suffix="/100" tone="blue" /><Metric label="预估利润率" value="38.6%" suffix="" tone="green" /></div><div className="grid grid-cols-2 gap-3"><Metric label="潜客数量" value="2,480" suffix="+" tone="blue" /><Metric label="风险等级" value="低" suffix="" tone="green" /></div></div>
      <div className="rounded-xl border border-border bg-card p-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold">海外客户增长</p><span className="text-[10px] text-emerald-600">+24.8%</span></div><div className="mt-2 h-28"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData}><defs><linearGradient id="fillBlue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={.22}/><stop offset="100%" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="name" hide/><YAxis hide/><Tooltip contentStyle={{ borderRadius: 10, border: '1px solid var(--border)', fontSize: 11 }} /><Area type="monotone" dataKey="value" stroke="var(--primary)" strokeWidth={2} fill="url(#fillBlue)" /></AreaChart></ResponsiveContainer></div><div className="mt-3 flex items-center gap-2 border-t border-border/70 pt-3 text-[10px] text-muted-foreground"><TrendingUp className="size-3 text-emerald-600" /> 近 6 个月有效潜客持续增长</div></div>
    </div>
  </div>
}
function Metric({ label, value, suffix, tone }: { label: string; value: string; suffix: string; tone: 'blue' | 'green' }) { return <div className="rounded-xl border border-border bg-card p-3"><p className="text-[10px] text-muted-foreground">{label}</p><p className={`mt-2 text-xl font-semibold ${tone === 'green' ? 'text-emerald-600' : 'text-foreground'}`}>{value}<span className="text-[10px] font-normal text-muted-foreground">{suffix}</span></p></div> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeTab, setActiveTab] = useState('市场机会')
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  const scrollTo = (id: string) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }) }
  return <main className="min-h-screen overflow-hidden">
    <header className="sticky top-0 z-50 border-b border-border/70 bg-background/90 backdrop-blur-md"><div className="container flex h-16 items-center justify-between"><a href="#top" className="flex items-center gap-2" aria-label="PickGlobal 首页"><span className="flex size-8 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Globe2 className="size-[18px]" /></span><span className="text-lg font-semibold tracking-tight">Pick<span className="text-primary">Global</span></span></a><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><button onClick={() => scrollTo('capabilities')} className="transition-colors hover:text-foreground">产品能力</button><button onClick={() => scrollTo('workflow')} className="transition-colors hover:text-foreground">工作流程</button><button onClick={() => scrollTo('scenes')} className="transition-colors hover:text-foreground">应用场景</button><button onClick={() => scrollTo('faq')} className="transition-colors hover:text-foreground">常见问题</button></nav><div className="hidden items-center gap-3 md:flex"><Button variant="ghost" onClick={() => scrollTo('contact')}>登录</Button><Button onClick={() => scrollTo('contact')}>免费体验 <ArrowRight data-icon="inline-end" /></Button></div><Button variant="ghost" size="icon" className="md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? '关闭菜单' : '打开菜单'}>{menuOpen ? <X /> : <Menu />}</Button></div>{menuOpen && <div className="border-t border-border bg-background px-5 py-5 md:hidden"><nav className="flex flex-col gap-4 text-sm"><button onClick={() => scrollTo('capabilities')} className="text-left">产品能力</button><button onClick={() => scrollTo('workflow')} className="text-left">工作流程</button><button onClick={() => scrollTo('scenes')} className="text-left">应用场景</button><button onClick={() => scrollTo('faq')} className="text-left">常见问题</button><Button onClick={() => scrollTo('contact')}>免费体验</Button></nav></div>}</header>
    <section id="top" className="hero-grid relative"><div className="container grid items-center gap-12 py-20 md:grid-cols-[.95fr_1.05fr] md:py-28"><div className="relative z-10 flex flex-col items-start gap-6"><span className="eyebrow"><Sparkles className="size-3.5" /> Oversea Market Selling</span><h1 className="max-w-xl text-balance text-4xl font-semibold leading-[1.1] tracking-[-.04em] md:text-6xl">从选品分析，到找到客户，<span className="text-primary">再到持续成交</span></h1><p className="max-w-lg text-pretty text-base leading-7 text-muted-foreground md:text-lg">PickGlobal 将商品评估、利润与税务分析、海外客户发现、AI 营销触达和流失召回整合到一个工作台。</p><div className="flex flex-wrap gap-3"><Button size="lg" onClick={() => scrollTo('analysis')}>开始分析商品 <ArrowRight data-icon="inline-end" /></Button><Button size="lg" variant="outline" onClick={() => scrollTo('workflow')}>查看完整流程</Button></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><MapPin className="size-3.5 text-emerald-600" /> 首期支持中国与美国市场</div></div><DashboardPreview /></div></section>
    <section id="workflow" className="section-padding"><div className="container"><SectionTitle eyebrow="End-to-end workflow" title="从一个商品，走完出海增长全链路" copy="把分散在多个工具里的判断、触达与跟进，收拢到一个清晰可执行的工作流。"/><div className="mt-14 grid gap-4 md:grid-cols-5">{[['01','导入商品','手动录入、CSV 或国内商品数据接口',PackageSearch],['02','智能分析','利润空间、税务、时效与市场风险',BarChart3],['03','发现客户','按地区和行业筛选潜在客户',Target],['04','AI 触达','生成个性化邮件与数字人内容',Mail],['05','流失召回','追踪互动并自动创建召回任务',RefreshCw]].map(([num,title,copy,Icon], i) => <div key={num as string} className="step-card relative"><div className="mb-5 flex items-center justify-between"><span className="text-xs font-semibold text-primary">{num as string}</span><span className="flex size-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-4" /></span></div><h3 className="font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy as string}</p>{i < 4 && <ChevronRight className="step-arrow" />}</div>)}</div></div></section>
    <section id="analysis" className="section-padding bg-muted/35"><div className="container grid items-center gap-12 md:grid-cols-[.82fr_1.18fr]"><div><span className="eyebrow">Product intelligence</span><h2 className="mt-4 text-balance text-3xl font-semibold tracking-tight md:text-5xl">每一次决策，都有数据依据</h2><p className="mt-5 text-pretty leading-7 text-muted-foreground">从市场热度到物流时效，PickGlobal 帮你把复杂的出海变量，转化为一份看得懂、能行动的商品报告。</p><ul className="mt-7 flex flex-col gap-4">{['识别更值得投入的市场机会','预估真实利润，提前规避隐性成本','用风险提示辅助团队做出稳健判断'].map(item => <li key={item} className="flex items-start gap-3 text-sm"><span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Check className="size-3" /></span>{item}</li>)}</ul></div><div className="report-card"><div className="flex flex-wrap gap-1 border-b border-border px-3 pt-3 md:px-5">{tabs.map(tab => <button key={tab} onClick={() => setActiveTab(tab)} className={`report-tab ${activeTab === tab ? 'report-tab-active' : ''}`}>{tab}</button>)}</div><div className="p-4 md:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-muted-foreground">{activeTab} · AI 分析摘要</p><h3 className="mt-2 text-xl font-semibold">美国市场机会良好</h3></div><span className="flex size-12 items-center justify-center rounded-2xl bg-emerald-50 text-lg font-semibold text-emerald-700">86</span></div><div className="mt-6 grid gap-4 md:grid-cols-[1fr_1fr]"><div className="rounded-xl border border-border p-3"><p className="text-xs font-medium">市场机会指数</p><div className="mt-4 h-32"><ResponsiveContainer width="100%" height="100%"><BarChart data={marketData} layout="vertical" margin={{ left: 10, right: 8 }}><XAxis type="number" hide/><YAxis dataKey="name" type="category" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: 'var(--muted-foreground)' }} width={48}/><Bar dataKey="value" fill="var(--primary)" radius={[0, 5, 5, 0]} barSize={10}/></BarChart></ResponsiveContainer></div></div><div className="rounded-xl border border-border p-3"><p className="text-xs font-medium">建议行动</p><div className="mt-4 flex flex-col gap-3 text-xs leading-5 text-muted-foreground"><div className="flex gap-2"><Zap className="size-4 shrink-0 text-emerald-600" />优先测试北美中高端渠道</div><div className="flex gap-2"><CircleDollarSign className="size-4 shrink-0 text-primary" />建议定价区间 $39–49</div><div className="flex gap-2"><Radar className="size-4 shrink-0 text-primary" />建立首批 120 个潜客名单</div></div></div></div></div></div></div></section>
    <section id="capabilities" className="section-padding"><div className="container"><SectionTitle eyebrow="Core capabilities" title="让增长动作，变成可复制的能力"/><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['商品与市场分析','看清市场机会与真实利润，减少试错成本',BarChart3,'深度洞察'],['海外客户发现','找到更匹配的行业买家，扩大有效客户池',Users,'精准获客'],['AI 营销触达','让每一次沟通更贴合客户与品牌语气',Mail,'高效转化'],['客户召回自动化','及时识别流失信号，把沉默客户带回来',BellRing,'持续成交']].map(([title,copy,Icon,label]) => <article key={title as string} className="feature-card"><div className="flex items-center justify-between"><span className="flex size-11 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Icon className="size-5" /></span><span className="text-[10px] font-medium text-muted-foreground">{label as string}</span></div><h3 className="mt-8 text-lg font-semibold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy as string}</p><ArrowRight className="mt-7 size-4 text-primary transition-transform group-hover:translate-x-1" /></article>)}</div></div></section>
    <section id="scenes" className="section-padding bg-navy text-white"><div className="container"><div className="max-w-xl"><span className="eyebrow eyebrow-dark">Built for growth teams</span><h2 className="mt-4 text-balance text-3xl font-semibold tracking-tight md:text-5xl">不论你从哪里出发，都能找到增长下一步</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['跨境电商卖家','快速验证新品，找到更有潜力的海外市场',Globe2],['外贸工厂','让优质产能连接更多精准买家',PackageSearch],['品牌出海团队','统一管理品牌触达与客户关系',Sparkles],['外贸服务商','为客户提供可量化的出海增长方案',Users]].map(([title,copy,Icon]) => <div key={title as string} className="dark-feature"><Icon className="size-5 text-cyan-300" /><h3 className="mt-8 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{copy as string}</p></div>)}</div></div></section>
    <section className="section-padding"><div className="container"><div className="platform-panel"><div className="max-w-xl"><span className="eyebrow">One workspace, everywhere</span><h2 className="mt-4 text-balance text-3xl font-semibold tracking-tight md:text-5xl">一个工作台，多端同步</h2><p className="mt-5 leading-7 text-muted-foreground">无论在办公室、路上还是客户现场，随时查看分析结果、跟进客户动作，不错过每一个增长机会。</p></div><div className="mt-10 grid grid-cols-3 gap-5 text-center md:mt-0 md:grid-cols-6">{[['Web',Monitor],['微信小程序',Globe2],['Android',Smartphone],['iOS',Smartphone],['macOS',Laptop],['Windows',Monitor]].map(([name,Icon]) => <div key={name as string} className="flex flex-col items-center gap-3 text-xs text-muted-foreground"><span className="flex size-12 items-center justify-center rounded-2xl border border-border bg-background text-primary"><Icon className="size-5" /></span>{name as string}</div>)}</div></div></div></section>
    <section className="border-y border-border bg-muted/30"><div className="container grid gap-4 py-8 sm:grid-cols-2 lg:grid-cols-4">{[['国内云基础设施',ShieldCheck],['数据集中管理',Radar],['操作记录可追溯',RefreshCw],['AI 分析与文案生成',Sparkles]].map(([text,Icon]) => <div key={text as string} className="flex items-center gap-3 text-sm font-medium"><Icon className="size-4 text-primary" />{text as string}</div>)}</div></section>
    <section id="faq" className="section-padding"><div className="container grid gap-12 md:grid-cols-[.7fr_1.3fr]"><div><span className="eyebrow">Questions, answered</span><h2 className="mt-4 text-balance text-3xl font-semibold tracking-tight md:text-5xl">还有问题？<br />我们来回答。</h2><p className="mt-5 leading-7 text-muted-foreground">如果你还想了解更多，欢迎联系我们预约一次产品演示。</p><Button className="mt-7" variant="outline" onClick={() => scrollTo('contact')}>预约演示 <ArrowRight data-icon="inline-end" /></Button></div><div className="flex flex-col border-t border-border">{faqs.map(([question, answer], i) => <div key={question} className="border-b border-border"><button className="flex w-full items-center justify-between gap-4 py-5 text-left text-sm font-medium" onClick={() => setOpenFaq(openFaq === i ? null : i)} aria-expanded={openFaq === i}><span>{question}</span><ChevronDown className={`size-4 shrink-0 text-muted-foreground transition-transform ${openFaq === i ? 'rotate-180' : ''}`} /></button>{openFaq === i && <p className="pb-5 pr-8 text-sm leading-6 text-muted-foreground">{answer}</p>}</div>)}</div></div></section>
    <section id="contact" className="section-padding"><div className="container"><div className="cta-panel"><div className="relative z-10 mx-auto flex max-w-2xl flex-col items-center gap-5 text-center"><span className="eyebrow eyebrow-dark">Start your next market</span><h2 className="text-balance text-3xl font-semibold tracking-tight text-white md:text-5xl">让每一个商品，都找到更合适的海外市场</h2><p className="text-slate-300">从第一次分析到客户召回，在一个工作台完成。</p><div className="flex flex-wrap justify-center gap-3"><Button size="lg" className="bg-white text-primary hover:bg-white/90" onClick={() => alert('感谢关注，体验申请已记录。')}>免费体验 <ArrowRight data-icon="inline-end" /></Button><Button size="lg" variant="outline" className="border-white/30 bg-white/10 text-white hover:bg-white/20 hover:text-white" onClick={() => alert('我们会尽快与您联系。')}>预约演示</Button></div></div></div></div></section>
    <footer className="border-t border-border"><div className="container grid gap-10 py-12 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><div className="flex items-center gap-2"><span className="flex size-8 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Globe2 className="size-4" /></span><span className="font-semibold">Pick<span className="text-primary">Global</span></span></div><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">选品分析与出海获客全链路闭环。</p></div><div><h3 className="text-sm font-semibold">产品</h3><div className="mt-4 flex flex-col gap-3 text-sm text-muted-foreground"><button className="text-left hover:text-foreground" onClick={() => scrollTo('capabilities')}>产品能力</button><button className="text-left hover:text-foreground" onClick={() => scrollTo('workflow')}>工作流程</button><button className="text-left hover:text-foreground" onClick={() => scrollTo('analysis')}>分析报告</button></div></div><div><h3 className="text-sm font-semibold">资源</h3><div className="mt-4 flex flex-col gap-3 text-sm text-muted-foreground"><button className="text-left hover:text-foreground" onClick={() => scrollTo('faq')}>常见问题</button><button className="text-left hover:text-foreground" onClick={() => scrollTo('scenes')}>应用场景</button><button className="text-left hover:text-foreground" onClick={() => scrollTo('contact')}>预约演示</button></div></div><div><h3 className="text-sm font-semibold">公司</h3><div className="mt-4 flex flex-col gap-3 text-sm text-muted-foreground"><span>pickgrobal.mornscience.top</span><span>hello@pickglobal.example</span><span>中国 · 美国</span></div></div></div><div className="container flex flex-col gap-2 border-t border-border py-6 text-xs text-muted-foreground md:flex-row md:items-center md:justify-between"><span>© 2026 PickGlobal. 保留所有权利。</span><span>首页展示数据均为样例数据</span></div></footer>
  </main>
}
