"""PostgreSQL catalog for project.md §5.

The live API still writes the JSON document store. These tables are the
cutover target: one tenant column, integer fen, and the state machines in §7.
`quality_score` from the document store maps to `score`, with `score_v2`
kept as the expand column. CloudBase collection names map in COLLECTION_MAP.
"""

from dataclasses import dataclass

CHANNELS = frozenset(
    {
        "ecommerce",
        "social",
        "expo",
        "agency",
        "enrichment",
        "geo_seo",
        "content_dh",
        "cross_border",
        "raas",
    }
)

# Board label for N is N%. The stored code stays an identifier.
METRIC_CODES = frozenset(
    {
        "N",
        "ActR",
        "TR",
        "OR",
        "AR",
        "QR",
        "ActR_cold",
        "RecR",
        "AnaT",
        "LeadT",
        "AcqT",
        "ActT",
        "RecT",
    }
)

LEDGER_SUBJECTS = frozenset({"usage", "agency_commission", "raas", "reversal"})

DEFAULT_FLAGS = {
    "auth.sso": False,
    "auth.mfa": False,
    "payment.raas": False,
    "selection.auto_deal": False,
    "acquisition.social": False,
    "acquisition.ecommerce": False,
    "acquisition.expo": False,
    "acquisition.agency": False,
    "ai.agent": False,
    "ai.finetune": False,
    "digital_human": False,
    "geo_seo": False,
    "raas": False,
    "global_multi_active": False,
}

COLLECTION_MAP = {
    "products": "products",
    "product_sources": "products",
    "analysis_reports": "selection_reports",
    "leads": "leads",
    "campaigns": "campaigns",
    "outreach_messages": "deliveries",
    "activation_jobs": "recalls",
    "recall_jobs": "recalls",
    "jobs": "jobs",
    "payment_orders": "payments",
    "usage_ledger": "ledger_entries",
    "metric_snapshots": "kpi_metrics",
    "commission_ledger": "ledger_entries",
    "raas_ledger": "ledger_entries",
}


def graph(spec: dict[str, tuple[str, ...]]) -> dict[str, frozenset[str]]:
    return {name: frozenset(dest) for name, dest in spec.items()}


USER_STATUS = graph(
    {
        "pending": ("active", "deleted"),
        "active": ("suspended", "deleted"),
        "suspended": ("active", "deleted"),
        "deleted": (),
    }
)
PAYMENT_STATUS = graph(
    {
        "created": ("pending", "failed"),
        "pending": ("succeeded", "failed"),
        "succeeded": ("refunded",),
        "failed": (),
        "refunded": (),
    }
)
REPORT_STATUS = graph(
    {
        "draft": ("analyzing",),
        "analyzing": ("completed",),
        "completed": ("acquired",),
        "acquired": (),
    }
)
TASK_STATUS = graph(
    {
        "created": ("running", "failed"),
        "running": ("paused", "completed", "failed"),
        "paused": ("running", "failed"),
        "completed": (),
        "failed": (),
    }
)
LEAD_STATUS = graph(
    {
        "new": ("scored", "lost"),
        "scored": ("qualified", "lost"),
        "qualified": ("contacted", "lost"),
        "contacted": ("replied", "lost", "recalled"),
        "replied": ("won", "lost", "recalled"),
        "won": ("recalled",),
        "lost": ("recalled",),
        "recalled": (),
    }
)
# pending_approval and approved sit on the published draft → scheduled chain.
# A send is illegal until a person has approved the copy.
CAMPAIGN_STATUS = graph(
    {
        "draft": ("pending_approval", "scheduled"),
        "pending_approval": ("approved", "draft"),
        "approved": ("scheduled", "sending"),
        "scheduled": ("sending", "paused"),
        "sending": ("sent", "paused"),
        "sent": ("completed",),
        "paused": ("sending", "scheduled"),
        "completed": (),
    }
)
RECALL_STATUS = graph(
    {
        "triggered": ("queued", "failed"),
        "queued": ("approved", "failed"),
        "approved": ("delivered", "failed"),
        "delivered": ("recovered", "failed"),
        "recovered": (),
        "failed": (),
    }
)
DEAL_STATUS = graph({"open": ("won", "lost"), "won": (), "lost": ()})
SUBSCRIPTION_STATUS = graph(
    {
        "trialing": ("active", "canceled"),
        "active": ("past_due", "canceled"),
        "past_due": ("active", "canceled"),
        "canceled": (),
    }
)
INVOICE_STATUS = graph({"draft": ("issued", "void"), "issued": ("void",), "void": ()})
REFUND_STATUS = graph(
    {
        "created": ("pending", "failed"),
        "pending": ("succeeded", "failed"),
        "succeeded": (),
        "failed": (),
    }
)
COUPON_STATUS = graph({"active": ("disabled",), "disabled": ()})
DELIVERY_STATUS = frozenset({"pending", "delivered", "bounced", "complained", "failed"})
EVENT_STATUS = frozenset({"received", "processed", "ignored"})
AI_STATUS = frozenset({"succeeded", "failed"})


@dataclass(frozen=True)
class Table:
    name: str
    columns: tuple[str, ...]
    primary_key: tuple[str, ...] = ("id",)
    # "tenant_id" on tenant rows, "id" on tenants, None on global catalogs.
    tenant_column: str | None = "tenant_id"
    soft_delete: bool = True
    append_only: bool = False
    operational: bool = True
    shared_read: bool = False
    allow_null_tenant: bool = False
    transitions: dict[str, frozenset[str]] | None = None
    statuses: frozenset[str] | None = None
    initial_status: str | None = None
    json_columns: tuple[str, ...] = ()
    fen_columns: tuple[str, ...] = ()
    fen_positive: tuple[str, ...] = ()
    decimal_columns: tuple[str, ...] = ()
    uniques: tuple[tuple[str, ...], ...] = ()
    channel_column: str | None = None
    extra_channels: frozenset[str] = frozenset()


def declared_statuses(table: Table) -> set[str] | None:
    if table.transitions is not None:
        nodes = set(table.transitions)
        for dest in table.transitions.values():
            nodes.update(dest)
        return nodes
    if table.statuses is not None:
        return set(table.statuses)
    return None


def _t(name: str, columns: tuple[str, ...], **kwargs) -> Table:
    return Table(name, columns, **kwargs)


TABLES: dict[str, Table] = {
    table.name: table
    for table in (
        _t(
            "schema_migrations",
            ("version", "applied_at"),
            primary_key=("version",),
            tenant_column=None,
            soft_delete=False,
            operational=False,
        ),
        _t(
            "tenants",
            (
                "id",
                "name",
                "plan",
                "trade_route",
                "status",
                "region",
                "compliance_region",
                "shard_key",
                "feature_flags",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
            ),
            tenant_column="id",
            transitions=USER_STATUS,
            initial_status="active",
            json_columns=("feature_flags",),
        ),
        _t(
            "users",
            (
                "id",
                "tenant_id",
                "email",
                "phone",
                "password_hash",
                "role",
                "status",
                "display_name",
                "cloudbase_user_id",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=USER_STATUS,
            initial_status="pending",
            uniques=(("tenant_id", "email"), ("cloudbase_user_id",)),
        ),
        _t(
            "roles",
            ("id", "tenant_id", "code", "name", "created_at", "shard_key", "region", "compliance_region"),
            soft_delete=False,
            shared_read=True,
            allow_null_tenant=True,
        ),
        _t(
            "permissions",
            ("id", "code", "resource", "action", "created_at"),
            tenant_column=None,
            soft_delete=False,
        ),
        _t(
            "role_permissions",
            ("role_id", "permission_id", "created_at"),
            primary_key=("role_id", "permission_id"),
            tenant_column=None,
            soft_delete=False,
        ),
        _t(
            "user_roles",
            (
                "id",
                "tenant_id",
                "user_id",
                "role_id",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            uniques=(("tenant_id", "user_id", "role_id"),),
        ),
        _t(
            "sessions",
            (
                "id",
                "tenant_id",
                "user_id",
                "token_hash",
                "expires_at",
                "revoked_at",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            uniques=(("token_hash",),),
        ),
        _t(
            "products",
            (
                "id",
                "tenant_id",
                "source",
                "title",
                "sku",
                "normalized_sku",
                "category",
                "target_price_usd",
                "cost_cny",
                "packaging_cny",
                "domestic_freight_cny",
                "international_freight_usd",
                "price_currency",
                "cost_currency",
                "origin_country",
                "target_market",
                "route",
                "incoterm",
                "tax_regime",
                "fx_usd_cny",
                "hs_code_hint",
                "context_version",
                "attributes",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            json_columns=("attributes",),
            decimal_columns=(
                "target_price_usd",
                "cost_cny",
                "packaging_cny",
                "domestic_freight_cny",
                "international_freight_usd",
                "fx_usd_cny",
            ),
            uniques=(("tenant_id", "normalized_sku"),),
        ),
        _t(
            "selection_reports",
            (
                "id",
                "tenant_id",
                "product_id",
                "route",
                "market",
                "net_margin",
                "net_profit_usd",
                "tax",
                "time_cost",
                "risk",
                "score",
                "status",
                "rules_version",
                "seed_ready",
                "seed_analysis_id",
                "fx_usd_cny",
                "metrics",
                "explanation",
                "explanation_model",
                "ai_model_version",
                "context_version",
                "requested_at",
                "finished_at",
                "acquired_at",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=REPORT_STATUS,
            initial_status="draft",
            json_columns=("metrics",),
            decimal_columns=("net_margin", "net_profit_usd", "tax", "fx_usd_cny"),
        ),
        _t(
            "acquisition_tasks",
            (
                "id",
                "tenant_id",
                "report_id",
                "channel",
                "status",
                "started_at",
                "finished_at",
                "seed_analysis_id",
                "channel_id",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=TASK_STATUS,
            initial_status="created",
            channel_column="channel",
        ),
        _t(
            "leads",
            (
                "id",
                "tenant_id",
                "task_id",
                "source_channel",
                "contact_name",
                "email",
                "phone",
                "company",
                "score",
                "score_v2",
                "qualified",
                "status",
                "market",
                "platform",
                "dedupe_key",
                "seed_analysis_id",
                "exclude_from_ar",
                "note",
                "opened_at",
                "replied_at",
                "won_at",
                "warmed_at",
                "agency_id",
                "channel_id",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=LEAD_STATUS,
            initial_status="new",
            decimal_columns=("score_v2",),
            uniques=(("tenant_id", "email"), ("tenant_id", "dedupe_key")),
            channel_column="source_channel",
        ),
        _t(
            "campaigns",
            (
                "id",
                "tenant_id",
                "task_id",
                "channel",
                "name",
                "purpose",
                "subject",
                "content",
                "status",
                "scheduled_at",
                "sent_at",
                "audience",
                "explanation_model",
                "ai_model_version",
                "agency_id",
                "channel_id",
                "seed_analysis_id",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=CAMPAIGN_STATUS,
            initial_status="draft",
            json_columns=("audience",),
            channel_column="channel",
            extra_channels=frozenset({"email"}),
        ),
        _t(
            "recalls",
            (
                "id",
                "tenant_id",
                "lead_id",
                "trigger",
                "recall_trigger",
                "status",
                "reason",
                "draft",
                "enqueued_at",
                "delivered_at",
                "recovered_at",
                "warmed_at",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=RECALL_STATUS,
            initial_status="triggered",
        ),
        _t(
            "deliveries",
            (
                "id",
                "tenant_id",
                "campaign_id",
                "lead_id",
                "recall_id",
                "channel",
                "status",
                "email",
                "body",
                "purpose",
                "ses_message_id",
                "delivered_at",
                "opened_at",
                "replied_at",
                "exclude_from_ar",
                "channel_id",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            statuses=DELIVERY_STATUS,
            initial_status="pending",
            uniques=(("tenant_id", "campaign_id", "lead_id"), ("tenant_id", "recall_id", "lead_id")),
            channel_column="channel",
            extra_channels=frozenset({"email"}),
        ),
        _t(
            "deals",
            (
                "id",
                "tenant_id",
                "lead_id",
                "amount_fen",
                "currency",
                "status",
                "won_at",
                "agency_id",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=DEAL_STATUS,
            initial_status="open",
            fen_columns=("amount_fen",),
        ),
        _t(
            "payments",
            (
                "id",
                "tenant_id",
                "user_id",
                "provider",
                "amount_fen",
                "currency",
                "status",
                "external_id",
                "idempotency_key",
                "plan_id",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=PAYMENT_STATUS,
            initial_status="created",
            fen_columns=("amount_fen",),
            uniques=(("tenant_id", "idempotency_key"),),
        ),
        _t(
            "subscriptions",
            (
                "id",
                "tenant_id",
                "plan",
                "status",
                "period_start",
                "period_end",
                "raas_rule",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=SUBSCRIPTION_STATUS,
            initial_status="active",
            json_columns=("raas_rule",),
        ),
        _t(
            "invoices",
            (
                "id",
                "tenant_id",
                "payment_id",
                "number",
                "amount_fen",
                "currency",
                "status",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=INVOICE_STATUS,
            initial_status="draft",
            fen_columns=("amount_fen",),
        ),
        _t(
            "refunds",
            (
                "id",
                "tenant_id",
                "payment_id",
                "amount_fen",
                "currency",
                "status",
                "idempotency_key",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=REFUND_STATUS,
            initial_status="created",
            fen_positive=("amount_fen",),
            uniques=(("tenant_id", "idempotency_key"),),
        ),
        _t(
            "coupons",
            (
                "id",
                "tenant_id",
                "code",
                "amount_off_fen",
                "percent_off",
                "status",
                "expires_at",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=COUPON_STATUS,
            initial_status="active",
            fen_columns=("amount_off_fen",),
            decimal_columns=("percent_off",),
            uniques=(("tenant_id", "code"),),
        ),
        _t(
            "payment_events",
            (
                "id",
                "tenant_id",
                "payment_id",
                "provider",
                "external_id",
                "signature_ok",
                "payload",
                "status",
                "idempotency_key",
                "created_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            soft_delete=False,
            append_only=True,
            statuses=EVENT_STATUS,
            initial_status="received",
            json_columns=("payload",),
        ),
        _t(
            "tax_records",
            (
                "id",
                "tenant_id",
                "payment_id",
                "regime",
                "amount_fen",
                "currency",
                "created_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            soft_delete=False,
            append_only=True,
            fen_columns=("amount_fen",),
        ),
        _t(
            "ledger_entries",
            (
                "id",
                "tenant_id",
                "amount_fen",
                "currency",
                "subject",
                "idempotency_key",
                "status",
                "signature",
                "agency_id",
                "raas_rule",
                "meta",
                "reverses_id",
                "created_by",
                "created_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            soft_delete=False,
            append_only=True,
            statuses=frozenset({"posted"}),
            initial_status="posted",
            json_columns=("raas_rule", "meta"),
            fen_positive=("amount_fen",),
            uniques=(("tenant_id", "idempotency_key"),),
        ),
        _t(
            "jobs",
            (
                "id",
                "tenant_id",
                "job_type",
                "status",
                "payload",
                "result",
                "error",
                "attempts",
                "idempotency_key",
                "scheduled_at",
                "started_at",
                "finished_at",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            transitions=TASK_STATUS,
            initial_status="created",
            json_columns=("payload", "result"),
            uniques=(("tenant_id", "idempotency_key"),),
        ),
        _t(
            "kpi_metrics",
            (
                "id",
                "tenant_id",
                "metric_code",
                "value",
                "period",
                "kpi_period",
                "dimensions",
                "created_at",
                "updated_at",
                "version",
                "shard_key",
                "region",
                "compliance_region",
            ),
            soft_delete=False,
            json_columns=("dimensions",),
            decimal_columns=("value",),
            uniques=(("tenant_id", "metric_code", "period"),),
        ),
        _t(
            "ai_models",
            ("id", "provider", "name", "model_version", "status", "created_at"),
            tenant_column=None,
            soft_delete=False,
            statuses=frozenset({"active", "retired"}),
            initial_status="active",
        ),
        _t(
            "ai_prompts",
            ("id", "name", "prompt_version", "body", "model_id", "created_at"),
            tenant_column=None,
            soft_delete=False,
        ),
        _t(
            "ai_calls",
            (
                "id",
                "tenant_id",
                "model",
                "prompt_version",
                "prompt_tokens",
                "completion_tokens",
                "latency_ms",
                "status",
                "ai_model_version",
                "request",
                "created_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            soft_delete=False,
            append_only=True,
            statuses=AI_STATUS,
            initial_status="succeeded",
            json_columns=("request",),
        ),
        _t(
            "ai_embeddings",
            (
                "id",
                "tenant_id",
                "source_table",
                "source_id",
                "model",
                "dims",
                "embedding",
                "created_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            soft_delete=False,
            append_only=True,
            json_columns=("embedding",),
        ),
        _t(
            "ai_feedback",
            (
                "id",
                "tenant_id",
                "call_id",
                "rating",
                "note",
                "created_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            soft_delete=False,
            append_only=True,
        ),
        _t(
            "ai_cache",
            (
                "id",
                "tenant_id",
                "cache_key",
                "model",
                "prompt_version",
                "response",
                "expires_at",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "shard_key",
                "region",
                "compliance_region",
            ),
            soft_delete=False,
            json_columns=("response",),
            uniques=(("tenant_id", "cache_key"),),
        ),
        _t(
            "ai_conversations",
            (
                "id",
                "tenant_id",
                "title",
                "model",
                "prompt_version",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
        ),
        _t(
            "ai_messages",
            (
                "id",
                "tenant_id",
                "conversation_id",
                "role",
                "content",
                "model",
                "prompt_version",
                "prompt_tokens",
                "completion_tokens",
                "created_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            soft_delete=False,
            append_only=True,
        ),
        _t(
            "suppressions",
            (
                "id",
                "tenant_id",
                "email",
                "reason",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            uniques=(("tenant_id", "email"),),
        ),
        _t(
            "objects",
            (
                "id",
                "tenant_id",
                "object_key",
                "content_hash",
                "mime",
                "byte_size",
                "created_by",
                "created_at",
                "updated_at",
                "version",
                "deleted_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            uniques=(("tenant_id", "object_key"),),
        ),
        _t(
            "audit_logs",
            (
                "id",
                "tenant_id",
                "user_id",
                "action",
                "resource",
                "ip",
                "request_id",
                "summary",
                "created_at",
                "shard_key",
                "region",
                "compliance_region",
            ),
            soft_delete=False,
            append_only=True,
            json_columns=("summary",),
        ),
    )
}


# roles and tenants use their own policies: system roles are readable, and
# the tenants row is isolated by id rather than a tenant_id column.
RLS_TABLES = tuple(
    name
    for name, table in TABLES.items()
    if table.tenant_column == "tenant_id" and name != "roles"
)
TOUCH_TABLES = tuple(
    name
    for name, table in TABLES.items()
    if "updated_at" in table.columns and not table.append_only
)
APPEND_TABLES = tuple(name for name, table in TABLES.items() if table.append_only)
